### ISSUE TITLE
tolist Error

### ISSUE THREAD

**Issue by azacha** [fischeversenker/intellisnake#7]
Error in connection handler
Traceback (most recent call last):
  File "C:\Users\azach\Anaconda3\lib\site-packages\websockets\server.py", line 195, in handler
    await self.ws_handler(self, path)
  File ".\websocket-server.py", line 32, in communication
    await self.processMessage(websocket, message["messageId"], message["type"], message["data"])
  File ".\websocket-server.py", line 61, in processMessage
    await self.sendMessage(websocket, messageId, "ack", survivors.tolist())
AttributeError: 'list' object has no attribute 'tolist'

**Comment by azacha** [comment]
Quick and Dirty Fix with Exception Handler?

**Comment by azacha** [comment]
Check Type before using toList()
